

spring: 
  cloud:
    admin:
      url: https://localhost:1105

management:
  endpoints:
    web:
      exposure: 
        include: "*"
          message: "welcome to microservices class"

        
          
